package gui;

import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;

import javax.swing.*;
import javax.swing.table.JTableHeader;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.*;

/**
 * Created by denjae on 16.01.14.
 */
public class Doctor {
    private JPanel mainPanel;
    private JTable output;
    private JButton buttonLeft;
    private JButton buttonRight;
    private java.util.List<Element> list;
    private Document doc;
    private File xmlFile;


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    private void createUIComponents() {
        String[][] values = fillJPanel();

        String[] title = new String[]{
                "Blutzucker", "Uhrzeit", "Datum"
        };

        output = new JTable(values, title);
        JTableHeader header = output.getTableHeader();
        output.setTableHeader(header);
    }

    private String[][] fillJPanel() {
        SAXBuilder b = new SAXBuilder();
        int j;

        try {
            doc = b.build(xmlFile);
        } catch (JDOMException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        //Anzahl der Werte auf max 20 begrenzen
        Element root = (Element) doc.getRootElement();
        list = root.getChildren("BZeintrag");

        //Liest die Werte aus der XML in das Array ein
        String[][] values = new String[20][3];


        //Variable j dient zum Vertauschen der Werte, somit werden die aktuellsten Werte oben statt unten ausgegeben
        if (list.size() <= 20) {
            j = list.size();
            for (int i = 0; i < list.size(); i++) {
                values[j][0] = list.get(i).getChildText("Blutzucker").toString();
                values[j][1] = list.get(i).getChildText("Uhrzeit").toString();
                values[j][2] = list.get(i).getChildText("Datum").toString();
                j--;
            }
        } else
            j = 19;
        for (int i = 0; i < 20; i++) {
            values[j][0] = list.get(list.size() - 20 + i).getChildText("Blutzucker").toString();
            values[j][1] = list.get(list.size() - 20 + i).getChildText("Uhrzeit").toString();
            values[j][2] = list.get(list.size() - 20 + i).getChildText("Datum").toString();
            j--;
        }
        return values;
    }

}
